<?php

namespace AppBundle\Repository;

/**
 * GladiatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GladiatorRepository extends \Doctrine\ORM\EntityRepository
{
}
